### ISSUE TITLE
Needs to look more like a skype

### ISSUE THREAD

**Issue by AlexMokin** [IdokkeI/skype#1]
Please try to make more like this screenshot. 
![image](https://user-images.githubusercontent.com/7272208/87569462-d4445780-c6cf-11ea-8627-6b1335a679b2.png)

You can use differnt images and icons. But colours margins and size should be close to the orginal messenger, skype in your case. You can pick different messenger if you'd like to. 

You use web version of the skype as a reference for margins, colours and even images and icons

**Comment by IdokkeI** [comment]
fixed

**Comment by ilya4321** [comment]
The goal is to check and improve skill of creating markup based on design or mockup.
Current UI looking is quite far from original, let's try to make it better! Thank you for the efforts!

**Comment by ilya4321** [comment]
it's better now, but it's still quite far from original 
![image](https://user-images.githubusercontent.com/5592397/89181263-02fd7180-d59c-11ea-8650-eed08c4b0c74.png)

**Comment by ilya4321** [comment]
![image](https://user-images.githubusercontent.com/5592397/92637380-6e480b00-f2e1-11ea-9825-666a5c749766.png)
Also 
 - please check fonts - you can make it more close to original
 - add more messages to message area to have a scroll bar

**Comment by IdokkeI** [comment]
check please

**Comment by ilya4321** [comment]
you have an issue with left panel now
https://www.screencast.com/t/P3uUVhk7y

**Comment by IdokkeI** [comment]
check please
