### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by AlexMokin** [IdokkeI/skype#2]
**Do not close the issue**

use web version of the skype as a reference for margins, colours and even images and icons

Your Messenger has to look as close as possible to the original.

This doesn't look very close to the original
![image](https://user-images.githubusercontent.com/7272208/88204113-8392a880-cc53-11ea-8ff5-2a9fbb48e49d.png)

**Comment by AlexMokin** [comment]
To have a reference here's the screenshot of the accepted task of other student who tried to copy skype

![image](https://user-images.githubusercontent.com/7272208/88204375-d704f680-cc53-11ea-990d-e61b409bd344.png)

**Comment by IdokkeI** [comment]
Fixed
